alias: Core - HA - Security Vulnerability Published
description: Sends Notification when a new security vulnerability is published
triggers:
  - trigger: state
    entity_id:
      - sensor.ha_latest_vulnerability_cve_id
conditions: []
actions:
  - action: notify.mobile_app_sm_s916b
    data:
      message: >-
        A new Home Assistant security advisory has been published: {{
        states('sensor.ha_latest_vulnerability_cve_id') }}
      data:
        color: "#2DF56D"
        channel: notifications
        actions:
          - action: URI
            title: CVE Details
            uri: " {{ states('sensor.ha_latest_vulnerability_cve') }} "
      title: 🔴 New Home Assistant Vulnerability!
mode: single
